Repository FRONTENDBOOTCAMP-13th/JS-13-A13C, pull requests merged in 2025-05, with the labels that each got.

#2 [docs] 리드미 최초 업로드
  README.md
Labels: documentation

#11 [feat] PR 테스트코드 완료.
  test-pjw.js
Labels: feature

#10 PR 테스트 완료했습니다.
  test-yebin.js
Labels: feature

#12 ✨ feat: test-youngchan
  test-youngchan.js
Labels: feature

#9 [docs] 글자 색상, 폰트 굵기 수정
  index.html
  src/main.ts
Labels: documentation

#19 [feat] 모달 컴포넌트 초기 세팅 #17
  src/components/modal/modal.html
  src/components/modal/modal.ts
  src/imges/close.webp
  src/style.css
Labels: component

#21 [feat] ingame 마크업 및 내 카드애니메이션
  src/imges/card-back.webp
  src/pages/ingame.html
  src/pages/ingame/ingame.ts
Labels: feature

#27 [feat] ingame.html 중간 푸쉬
  package-lock.json
  package.json
  src/pages/ingame.html
  src/pages/ingame/ingame.ts
  src/style.css
Labels: feature

#36 [Feat] lobby ksy
  index.html
  src/pages/lobby.html
  src/pages/rule.html
Labels: documentation, feature, fix

#51 Remove/imgError ksy
  index.html
  public/imges/card-1.webp
  public/imges/card-2.webp
  public/imges/card-3.webp
  public/imges/card-4.webp
  public/imges/card-5.webp
  public/imges/card-6.webp
  public/imges/card-7.webp
  public/imges/card-8.webp
  public/imges/card-back.webp
  public/imges/chat-btn.svg
  public/imges/close-white.svg
  public/imges/close.webp
  public/imges/frame.webp
  public/imges/main-backgrund-2.webp
  public/imges/main-backgrund.webp
  public/imges/score-board.webp
  src/components/modal/modal.html
  src/pages/ingame.html
  src/pages/ingame/ingame.ts
  src/pages/lobby.html
  src/pages/rule.html
Labels: bug, documentation, fix

#60 [merge] Feat/score-table-jyb 중간 병합
  src/components/score-table/round/round-table.html
  src/components/score-table/round/round-table.ts
  src/components/score-table/score-table.html
  src/components/score-table/score-table.ts
  src/components/score-table/test-ingame.html
  src/pages/ingame/A13C-chat.ts
  src/pages/ingame/chat.ts
Labels: component

#61 Docs/ingame-UI-ksy
  src/components/score-table/score-table.html
  src/pages/ingame.html
Labels: documentation

#65 [feat] ingame.html 추가작업
  src/pages/ingame.html
  src/pages/ingame/ingame.ts
Labels: feature

#66 [bug] ingame 충돌 수정
  src/pages/ingame.html
Labels: bug

#67 [bug] 카드선택 버그 수정 및 8초타이머 세팅
  src/pages/ingame.html
  src/pages/ingame/ingame.ts
Labels: bug

#68 [feat] gamelogic
  src/pages/ingame.html
  src/pages/ingame/chat.ts
  src/pages/ingame/time-ingame.ts
Labels: feature

#69 Comment/annotation ksy
  src/pages/ingame/ingame-logic.ts
  src/pages/rule.html
Labels: bug, documentation, feature

#72 [fix] sessionStorage로 변경 및 새로고침 기능 개선
  src/pages/ingame/chat.ts
Labels: bug, fix

#77 [feat] 웹소켓 연결 (중간커밋)
  .vscode/settings.json
  src/pages/ingame.html
  src/pages/ingame/chat.ts
  src/pages/ingame/ingame-logic.ts
  src/pages/ingame/ingame-server.ts
Labels: feature

#75 [bugfix] session storage로 변경
  src/components/score-table/score-table.ts
Labels: bug

#80 [feat] point 기능 테스트
  src/pages/ingame/winning-point/test.html
  src/pages/ingame/winning-point/test.ts
  src/pages/ingame/winning-point/winning-point.ts
Labels: documentation, feature

#83 [Feat] 빌드 명령어 수정
  package.json
Labels: documentation, feature

#96 [feat] 승점 테이블 로직 구현
  src/components/score-table/round/round-table.html
  src/components/score-table/round/round-table.ts
  src/components/score-table/score-table.ts
  src/components/score-table/test-ingame.html
  src/pages/ingame/winning-point.ts
  src/pages/ingame/winning-point/test.html
  src/pages/ingame/winning-point/test.ts
Labels: component, feature

#97 [bug] 상대 닉네임 오류 (진행중)
  src/pages/ingame.html
  src/pages/ingame/chat.ts
  src/pages/ingame/ingame-server.ts
Labels: bug

#100 [feat] round증가 및 최종순위 표시
  src/pages/ingame/round-and-ranking.ts
Labels: feature

#104 [fix]round-and-ranking파일 중복 구현 수정완료
  src/pages/ingame/round-and-ranking.ts
Labels: bug, fix

#107 [feat] 채팅에 autoClose 추가
  src/pages/ingame/A13C-chat.ts
  src/pages/ingame/chat.ts
Labels: feature, fix

#109 [feat] 라운드 테이블 추가
  src/components/score-table/round/round-table.ts
  src/pages/ingame.html
Labels: feature, fix

#111 Fix/UI infinity ksy
  src/components/score-table/test-ingame.html
  src/pages/ingame.html
  src/pages/ingame/ingame-server.ts
  src/pages/ingame/ingame-ui.ts
  vite.config.js
Labels: bug, documentation, feature, fix

#117 [docs] 파일 정리
  package-lock.json
  src/components/modal/modal.ts
  src/pages/ingame.html
  src/pages/ingame/chat.ts
  src/pages/ingame/winning-point.ts
  src/pages/lobby.html
  src/script/A13C-chat.ts
  src/script/ingame/chat.ts
  src/script/ingame/index.ts
  src/script/ingame/ingame-ui.ts
  src/script/ingame/round-table.ts
  src/script/ingame/score-table.ts
  src/script/ingame/store.ts
  src/script/ingame/winning-point.ts
  src/script/lobby/create-room-modal.ts
  src/script/lobby/index.ts
  src/script/lobby/join-room-modal.ts
  src/script/lobby/lobby-scroll.ts
Labels: feature

#119 [bugfix] 경로 및 함수 수정
  src/components/score-table/score-table.ts
  src/script/ingame/round-table.ts
Labels: bug

#121 Docs/annotation claer ksy
  src/components/score-table/round/round-table.html
  src/components/score-table/score-table.html
  src/pages/ingame.html
  src/pages/ingame/ingame-server.ts
  src/pages/ingame/ingame-ui.ts
  src/pages/ingame/ingame.ts
  src/pages/ingame/round-and-ranking.ts
  src/pages/lobby/lobby-scroll.ts
  src/pages/lobby/lobby.ts
  src/script/chat.ts
  src/script/ingame/index.ts
  src/script/ingame/ingame-ui.ts
  vite.config.js
Labels: refactor

#123 [fix] 정리된 파일에 맞게 채팅 수정
  src/pages/chat.html
  src/pages/ingame.html
  src/pages/lobby.html
  src/script/A13C-chat.ts
  src/script/ingame/chat.ts
  src/script/ingame/index.ts
  src/script/ingame/ingame-ui.ts
Labels: bug, fix

#125 [fix] index.ts 오류 수정 완료
  src/script/ingame/index.ts
Labels: bug, fix

#129 [Feat] 게임시작 및 라운드 오버레이
  src/main.ts
  src/pages/ingame.html
  src/script/chat.ts
  src/script/ingame/round-start.ts
  src/script/lobby/create-room-modal.ts
Labels: feature

#132 [fix] 게임시작창 수정 (참여할때 로컬스토리지 set)
  src/script/lobby/join-room-modal.ts
Labels: fix

#133 [feat] 누적 승점 테이블 닉네임 연동
  src/pages/ingame.html
  src/script/ingame/round-table.ts
  src/script/ingame/score-table.ts
Labels: bug, feature

#134 [TODO] 중간 커밋
  src/pages/ingame.html
  src/script/ingame/ingame-ui.ts
  src/script/ingame/round-start.ts
Labels: bug, documentation, feature, fix

#139 [feat] 라운드 테이블 함수 추가
  src/script/ingame/round-table.ts
Labels: feature

#141 [fix] timer 삭제
  src/pages/ingame.html
Labels: fix

#137 [docs] readme
  README.md
Labels: documentation

#142 [fix]chat-count
  src/script/ingame/chat.ts
  src/script/ingame/index.ts
Labels: bug

#143 Docs/UI ksy
  public/imges/card-0.webp
  public/imges/card-undefined.webp
  src/pages/ingame.html
  src/pages/lobby.html
  src/script/ingame/ingame-ui.ts
Labels: feature

#144 [bug] 중간 커밋
  src/script/ingame/chat.ts
  src/script/ingame/index.ts
  src/script/ingame/ingame-ui.ts
Labels: bug, fix

#155 [merge] Docs/readme jyb 1
  README.md
  public/imges/규칙.gif
  public/imges/라운드테이블+라운드표시.gif
  public/imges/방장-방생성.gif
  public/imges/방장아님.gif
  public/imges/스코어테이블호버.gif
  public/imges/카드 두장.gif
  public/imges/카드 한장.gif
Labels: documentation

#157 Feat/meta ksy
  index.html
  public/A13C_og_large_image.png
  public/A13C_og_twitter_large_image.png
  public/apple-touch-icon-120x120.png
  public/apple-touch-icon-152x152.png
  public/apple-touch-icon-167x167.png
  public/apple-touch-icon-180x180.png
  public/googleec71e15bf4613958.html
  public/robots.txt
  public/sitemap.xml
Labels: feature
